<template>
  <q-page class="q-pa-lg">
    <h4 class="q-mt-none q-mb-md text-weight-bold">About Qwitter</h4>
    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultricies metus velit, egestas iaculis mi pellentesque at. Etiam eget bibendum lectus. Morbi sit amet tortor eget mauris egestas porta. Vestibulum ultrices lobortis vulputate. Praesent cursus felis sed suscipit elementum. Cras in nibh sit amet mi tempus ultricies. Morbi imperdiet hendrerit interdum. Nullam ipsum orci, ornare at pellentesque ut, eleifend sed purus. Cras eros purus, pharetra et nisi quis, laoreet malesuada libero. Ut ut rutrum dui, molestie dictum nulla. Aliquam non ex vel dolor dapibus convallis in ac eros.

Morbi nec mattis magna, nec consectetur leo. Maecenas viverra tortor urna, ac ullamcorper urna pretium ac. Fusce imperdiet justo non turpis egestas, in ullamcorper eros iaculis. Quisque tempor, augue vitae porttitor facilisis, nisi mauris scelerisque justo, vitae iaculis nunc massa sit amet dolor. Sed vestibulum nunc sed nulla fermentum facilisis. Fusce sit amet risus enim. Sed dictum euismod iaculis. Sed sem lorem, blandit sit amet commodo vel, interdum eu quam. Donec nisl augue, faucibus vitae est et, interdum interdum tellus. Aenean libero risus, dictum vulputate lorem sit amet, tincidunt tempus mauris. Sed in ipsum nec felis molestie maximus vitae eget nunc. Suspendisse blandit ex ac felis ultricies, vitae euismod erat dapibus. In ut lobortis magna. Fusce pretium suscipit lectus eget pulvinar.

Pellentesque nisl ex, viverra eget augue sollicitudin, varius rutrum velit. Proin feugiat consequat aliquam. Sed pellentesque urna vel nibh porta convallis. Vestibulum feugiat libero sit amet tellus accumsan, quis condimentum augue pharetra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tellus nibh, tempor in porta eget, dapibus consectetur elit. Cras eu sapien sagittis ante posuere aliquam. Maecenas malesuada diam nec arcu maximus, placerat sagittis velit laoreet. Vivamus fringilla libero ut tellus consectetur, ac tristique justo sollicitudin. </p>
    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultricies metus velit, egestas iaculis mi pellentesque at. Etiam eget bibendum lectus. Morbi sit amet tortor eget mauris egestas porta. Vestibulum ultrices lobortis vulputate. Praesent cursus felis sed suscipit elementum. Cras in nibh sit amet mi tempus ultricies. Morbi imperdiet hendrerit interdum. Nullam ipsum orci, ornare at pellentesque ut, eleifend sed purus. Cras eros purus, pharetra et nisi quis, laoreet malesuada libero. Ut ut rutrum dui, molestie dictum nulla. Aliquam non ex vel dolor dapibus convallis in ac eros.

Morbi nec mattis magna, nec consectetur leo. Maecenas viverra tortor urna, ac ullamcorper urna pretium ac. Fusce imperdiet justo non turpis egestas, in ullamcorper eros iaculis. Quisque tempor, augue vitae porttitor facilisis, nisi mauris scelerisque justo, vitae iaculis nunc massa sit amet dolor. Sed vestibulum nunc sed nulla fermentum facilisis. Fusce sit amet risus enim. Sed dictum euismod iaculis. Sed sem lorem, blandit sit amet commodo vel, interdum eu quam. Donec nisl augue, faucibus vitae est et, interdum interdum tellus. Aenean libero risus, dictum vulputate lorem sit amet, tincidunt tempus mauris. Sed in ipsum nec felis molestie maximus vitae eget nunc. Suspendisse blandit ex ac felis ultricies, vitae euismod erat dapibus. In ut lobortis magna. Fusce pretium suscipit lectus eget pulvinar.

Pellentesque nisl ex, viverra eget augue sollicitudin, varius rutrum velit. Proin feugiat consequat aliquam. Sed pellentesque urna vel nibh porta convallis. Vestibulum feugiat libero sit amet tellus accumsan, quis condimentum augue pharetra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tellus nibh, tempor in porta eget, dapibus consectetur elit. Cras eu sapien sagittis ante posuere aliquam. Maecenas malesuada diam nec arcu maximus, placerat sagittis velit laoreet. Vivamus fringilla libero ut tellus consectetur, ac tristique justo sollicitudin. </p>
    <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi ultricies metus velit, egestas iaculis mi pellentesque at. Etiam eget bibendum lectus. Morbi sit amet tortor eget mauris egestas porta. Vestibulum ultrices lobortis vulputate. Praesent cursus felis sed suscipit elementum. Cras in nibh sit amet mi tempus ultricies. Morbi imperdiet hendrerit interdum. Nullam ipsum orci, ornare at pellentesque ut, eleifend sed purus. Cras eros purus, pharetra et nisi quis, laoreet malesuada libero. Ut ut rutrum dui, molestie dictum nulla. Aliquam non ex vel dolor dapibus convallis in ac eros.

Morbi nec mattis magna, nec consectetur leo. Maecenas viverra tortor urna, ac ullamcorper urna pretium ac. Fusce imperdiet justo non turpis egestas, in ullamcorper eros iaculis. Quisque tempor, augue vitae porttitor facilisis, nisi mauris scelerisque justo, vitae iaculis nunc massa sit amet dolor. Sed vestibulum nunc sed nulla fermentum facilisis. Fusce sit amet risus enim. Sed dictum euismod iaculis. Sed sem lorem, blandit sit amet commodo vel, interdum eu quam. Donec nisl augue, faucibus vitae est et, interdum interdum tellus. Aenean libero risus, dictum vulputate lorem sit amet, tincidunt tempus mauris. Sed in ipsum nec felis molestie maximus vitae eget nunc. Suspendisse blandit ex ac felis ultricies, vitae euismod erat dapibus. In ut lobortis magna. Fusce pretium suscipit lectus eget pulvinar.

Pellentesque nisl ex, viverra eget augue sollicitudin, varius rutrum velit. Proin feugiat consequat aliquam. Sed pellentesque urna vel nibh porta convallis. Vestibulum feugiat libero sit amet tellus accumsan, quis condimentum augue pharetra. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce tellus nibh, tempor in porta eget, dapibus consectetur elit. Cras eu sapien sagittis ante posuere aliquam. Maecenas malesuada diam nec arcu maximus, placerat sagittis velit laoreet. Vivamus fringilla libero ut tellus consectetur, ac tristique justo sollicitudin. </p>
  </q-page>
</template>

<script>
import { defineComponent } from 'vue';

export default defineComponent({
  name: 'PageAbout'
})
</script>
